const express = require("express");
require("dotenv").config();
const { connectDb } = require("./db");
const { userRouter } = require("./routes/user.route");
const { authCheck } = require("./middleware/authentication");
const cors = require("cors");
const { productModel } = require("./model/product.model");

const app = express();
app.use(cors());
app.use(express.json());

app.get("/krdo", async (req, res) => {
  await productModel.insertMany([
    {
      image:
        "https://www.yoox.com/images/items/30/30029297tq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Maxi Skirts",
      oldprice: "US$ 1.629,00",
      off: "52% OFF",
      newprice: "780",
      category: "women",
      size: "40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/49/49845116xq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Blazers",
      oldprice: "US$ 1.124,00",
      off: "47% OFF",
      newprice: "594",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15293924jw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Midi dresses",
      oldprice: "US$ 1.370,00",
      off: "50% OFF",
      newprice: "673",
      category: "women",
      size: "36 38 40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10107496fg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Blouses",
      oldprice: "US$ 449,00",
      off: "48% OFF",
      newprice: "229",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14334990cl_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Sweaters",
      oldprice: "US$ 449,00",
      off: "48% OFF",
      newprice: "231",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30028645nm_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Casual pants",
      oldprice: "US$ 907,00",
      off: "31% OFF",
      newprice: "619",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10106553oa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Blouses",
      oldprice: "US$ 367,00",
      off: "49% OFF",
      newprice: "187",
      category: "women",
      size: "40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10106797sa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "T-shirts",
      oldprice: "US$ 449,00",
      off: "48% OFF",
      newprice: "229",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14333479sw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Cardigans",
      oldprice: "US$ 998,00",
      off: "48% OFF",
      newprice: "512",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10113969we_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Shirt",
      oldprice: "US$ 1.280,00",
      off: "27% OFF",
      newprice: "929",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30023727lm_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Shorts & Bermuda",
      oldprice: "US$ 625,00",
      off: "31% OFF",
      newprice: "427",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30038856we_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Denim pants",
      oldprice: "US$ 778,00",
      off: "31% OFF",
      newprice: "531",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16228014qh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Coats",
      oldprice: "US$ 3.283,00",
      off: "34% OFF",
      newprice: "2.143",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15294494jt_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Midi dresses",
      oldprice: "US$ 1.238,00",
      off: "50% OFF",
      newprice: "608",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14329438pl_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "GUCCI",
      microcategory: "Sweaters",
      oldprice: "US$ 1.124,00",
      off: "33% OFF",
      newprice: "742",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30044639og_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "GUCCI",
      microcategory: "Casual pants",
      oldprice: "US$ 998,00",
      off: "34% OFF",
      newprice: "658",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10130323lh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Shirt",
      oldprice: "US$ 910,00",
      off: "49% OFF",
      newprice: "463",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10099340nb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Blouses",
      oldprice: "US$ 1.238,00",
      off: "49% OFF",
      newprice: "631",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10121918wb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Hooded sweatshirts",
      oldprice: "US$ 958,00",
      off: "27% OFF",
      newprice: "696",
      category: "women",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10113934xg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "GUCCI",
      microcategory: "T-shirts",
      oldprice: "US$ 617,00",
      off: "27% OFF",
      newprice: "448",
      category: "women",
      size: "XS",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10109111cn_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Shirt",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/54/54194471rl_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Jumpsuits/one pieces",
      oldprice: "US$ 2.399,00",
      off: "28% OFF",
      newprice: "1.722",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30022325nx_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "GUCCI",
      microcategory: "Casual pants",
      oldprice: "US$ 973,00",
      off: "34% OFF",
      newprice: "635",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15219750cq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "GUCCI",
      microcategory: "Short dresses",
      oldprice: "US$ 2.757,00",
      off: "43% OFF",
      newprice: "1.564",
      category: "women",
      size: "40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14341534kc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "AGNONA",
      microcategory: "Cashmere blends",
      oldprice: "US$ 556,00",
      off: "45% OFF",
      newprice: "305",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14341645gm_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "AGNONA",
      microcategory: "Sweaters",
      oldprice: "US$ 701,00",
      off: "45% OFF",
      newprice: "385",
      category: "women",
      size: "36 38 40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10125047fq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Sweaters",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10152867jp_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ARMANI JEANS",
      microcategory: "T-shirts",
      oldprice: "US$ 109,00",
      off: "33% OFF",
      newprice: "72",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30035364du_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Denim shorts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30035420ha_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15299417xd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Short dresses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15299399jp_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Long dresses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30035284vo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30035302le_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15299452jq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Midi dresses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30035411ni_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15299448dq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Midi dresses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15299440xw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Midi dresses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15299425uk_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Midi dresses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10125035qj_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Tank tops",
      oldprice: "",
      off: "",
      newprice: "",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30024778qe_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ARMANI JEANS",
      microcategory: "Denim skirts",
      oldprice: "US$ 186,00",
      off: "27% OFF",
      newprice: "135",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10136279kh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ARMANI JEANS",
      microcategory: "Tops",
      oldprice: "US$ 175,00",
      off: "34% OFF",
      newprice: "114",
      category: "women",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30038860wa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Denim pants",
      oldprice: "US$ 191,00",
      off: "27% OFF",
      newprice: "139",
      category: "women",
      size: "XS",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30022369um_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "DKNY",
      microcategory: "Leggings",
      oldprice: "US$ 98,00",
      off: "27% OFF",
      newprice: "71",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041359ld_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ARMANI JEANS",
      microcategory: "Denim pants",
      oldprice: "US$ 215,00",
      off: "26% OFF",
      newprice: "157",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30033081lb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ARMANI JEANS",
      microcategory: "Denim pants",
      oldprice: "US$ 250,00",
      off: "27% OFF",
      newprice: "182",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041854oa_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 163,00",
      off: "34% OFF",
      newprice: "106",
      category: "women",
      size: "40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041957mc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042043he_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "36 38 40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041542vu_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042050jo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10134824eb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Hooded sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30045039bv_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Cropped pants & culottes",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10140237th_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 189,00",
      off: "27% OFF",
      newprice: "137",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041525he_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/54/54194865qi_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim overalls",
      oldprice: "US$ 328,00",
      off: "28% OFF",
      newprice: "235",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30044673cb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10138048uw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 151,00",
      off: "27% OFF",
      newprice: "109",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041835im_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30045054jx_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 252,00",
      off: "34% OFF",
      newprice: "165",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041607ca_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Bootcut Jeans",
      oldprice: "US$ 163,00",
      off: "34% OFF",
      newprice: "106",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041744wo_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Cropped jeans",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041453wg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046418ri_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 214,00",
      off: "34% OFF",
      newprice: "140",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046394wi_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim shorts",
      oldprice: "US$ 113,00",
      off: "34% OFF",
      newprice: "74",
      category: "women",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133654cg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 163,00",
      off: "27% OFF",
      newprice: "118",
      category: "women",
      size: "XS",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041724if_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15303565rv_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Short dresses",
      oldprice: "US$ 151,00",
      off: "27% OFF",
      newprice: "109",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15303839sc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Midi dresses",
      oldprice: "US$ 163,00",
      off: "27% OFF",
      newprice: "118",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16232141gl_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim jackets",
      oldprice: "US$ 201,00",
      off: "30% OFF",
      newprice: "140",
      category: "women",
      size: "40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042430gg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 125,00",
      off: "34% OFF",
      newprice: "82",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16232472ua_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim jackets",
      oldprice: "US$ 176,00",
      off: "30% OFF",
      newprice: "123",
      category: "women",
      size: "36 38 40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10134335dc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042033qb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16232477bf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Full-length jackets",
      oldprice: "US$ 227,00",
      off: "30% OFF",
      newprice: "158",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14342891mg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweaters",
      oldprice: "US$ 151,00",
      off: "34% OFF",
      newprice: "99",
      category: "women",
      size: "40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14341683xk_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweaters",
      oldprice: "US$ 151,00",
      off: "34% OFF",
      newprice: "99",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042007on_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10122455kj_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CALVIN KLEIN",
      microcategory: "Blouses",
      oldprice: "US$ 127,00",
      off: "34% OFF",
      newprice: "83",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133776ja_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042189uq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10138025gc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweaters",
      oldprice: "US$ 151,00",
      off: "34% OFF",
      newprice: "99",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133890kk_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Tank tops",
      oldprice: "US$ 38,00",
      off: "21% OFF",
      newprice: "30",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/15/15303901up_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Midi dresses",
      oldprice: "US$ 163,00",
      off: "27% OFF",
      newprice: "118",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10134810qo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Hooded sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041461jp_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041537fl_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041533vr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10134974dj_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Hooded sweatshirts",
      oldprice: "US$ 163,00",
      off: "27% OFF",
      newprice: "118",
      category: "women",
      size: "XS",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10110830bo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 161,00",
      off: "27% OFF",
      newprice: "117",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042407qw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133784sq_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046742qa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041589qp_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 214,00",
      off: "34% OFF",
      newprice: "140",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046641sm_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "36 38 40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041828bf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Cropped jeans",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133772ff_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 113,00",
      off: "27% OFF",
      newprice: "82",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041441nm_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041992wa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "40 42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041482mo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133779pl_14_r.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042190af_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046440gn_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 163,00",
      off: "34% OFF",
      newprice: "106",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133746kf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 151,00",
      off: "27% OFF",
      newprice: "109",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10138056qc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Short dresses",
      oldprice: "US$ 100,00",
      off: "27% OFF",
      newprice: "73",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046297vg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10133741kb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 125,00",
      off: "27% OFF",
      newprice: "91",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046621ro_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "38 40 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042429rd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10110821jx_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Sweatshirts",
      oldprice: "US$ 136,00",
      off: "27% OFF",
      newprice: "98",
      category: "women",
      size: "38 40 42 44 46",
    },
    {
      image:
        "https://www.yoox.com/images/items/48/48312163ec_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MARNI",
      microcategory: "Socks & tights",
      oldprice: "US$ 76,00",
      off: "47% OFF",
      newprice: "40",
      category: "women",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30047190wk_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "XS",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30045346te_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Baggy",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30024611bp_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 186,00",
      off: "34% OFF",
      newprice: "121",
      category: "women",
      size: "XS M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30021519pr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 186,00",
      off: "34% OFF",
      newprice: "121",
      category: "women",
      size: "XS S M L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30046407bc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 163,00",
      off: "34% OFF",
      newprice: "106",
      category: "women",
      size: "27W-30L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042422qr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 189,00",
      off: "34% OFF",
      newprice: "123",
      category: "women",
      size: "27W-32L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30042412oi_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Bootcut Jeans",
      oldprice: "US$ 201,00",
      off: "34% OFF",
      newprice: "131",
      category: "women",
      size: "28W-30L",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10122431ax_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ZANONE",
      microcategory: "T-shirts",
      oldprice: "US$ 209,00",
      off: "38% OFF",
      newprice: "129",
      category: "women",
      size: "42",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30041658ml_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "REPLAY",
      microcategory: "Denim pants",
      oldprice: "US$ 176,00",
      off: "34% OFF",
      newprice: "115",
      category: "women",
      size: "27W-32L",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16227946ki_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Biker jackets",
      oldprice: "US$ 4.255,00",
      off: "40% OFF",
      newprice: "2.519",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16229417eq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Jackets",
      oldprice: "US$ 2.411,00",
      off: "34% OFF",
      newprice: "1.574",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30022941ov_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Casual pants",
      oldprice: "US$ 947,00",
      off: "32% OFF",
      newprice: "638",
      category: "men",
      size: "XXS XS S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46912556kc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Sunglasses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "59",
    },
    {
      image:
        "https://www.yoox.com/images/items/45/45745670jf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "FENDI",
      microcategory: "Handbags",
      oldprice: "US$ 1.579,00",
      off: "27% OFF",
      newprice: "1.147",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30012477qh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Cargo",
      oldprice: "US$ 1.516,00",
      off: "29% OFF",
      newprice: "1.076",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17557235bb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Sandals",
      oldprice: "US$ 869,00",
      off: "27% OFF",
      newprice: "631",
      category: "men",
      size: "42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17524779ed_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CHURCH'S",
      microcategory: "Sneakers",
      oldprice: "US$ 985,00",
      off: "27% OFF",
      newprice: "715",
      category: "men",
      size: "40 41 41.5 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17560113uk_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "TRICKER'S",
      microcategory: "Boots",
      oldprice: "US$ 673,00",
      off: "34% OFF",
      newprice: "439",
      category: "men",
      size: "41 41 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17551868kk_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CHURCH'S",
      microcategory: "Loafers",
      oldprice: "US$ 1.046,00",
      off: "27% OFF",
      newprice: "759",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17524827tj_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CHURCH'S",
      microcategory: "Sneakers",
      oldprice: "US$ 985,00",
      off: "27% OFF",
      newprice: "715",
      category: "men",
      size: "43",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17526151lk_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CHURCH'S",
      microcategory: "Loafers",
      oldprice: "US$ 1.167,00",
      off: "27% OFF",
      newprice: "847",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17539611hr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CHURCH'S",
      microcategory: "Laced shoes",
      oldprice: "US$ 1.137,00",
      off: "27% OFF",
      newprice: "825",
      category: "men",
      size: "40.5",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17531363fr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "CHURCH'S",
      microcategory: "Loafers",
      oldprice: "US$ 637,00",
      off: "27% OFF",
      newprice: "462",
      category: "men",
      size: "45.5",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10135785bd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Sweatshirts",
      oldprice: "US$ 796,00",
      off: "31% OFF",
      newprice: "544",
      category: "men",
      size: "XL",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10116732xi_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Shirt",
      oldprice: "US$ 932,00",
      off: "31% OFF",
      newprice: "637",
      category: "men",
      size: "L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30043108dw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Shorts & Bermuda",
      oldprice: "US$ 748,00",
      off: "40% OFF",
      newprice: "443",
      category: "men",
      size: "M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30029515og_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Casual pants",
      oldprice: "US$ 824,00",
      off: "40% OFF",
      newprice: "488",
      category: "men",
      size: "50",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30035287ct_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Casual pants",
      oldprice: "US$ 1.151,00",
      off: "40% OFF",
      newprice: "682",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30032514ow_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "FENDI",
      microcategory: "Denim pants",
      oldprice: "US$ 771,00",
      off: "34% OFF",
      newprice: "503",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30023126ix_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "FENDI",
      microcategory: "Casual pants",
      oldprice: "US$ 1.452,00",
      off: "34% OFF",
      newprice: "948",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/45/45743011ns_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "FENDI",
      microcategory: "Handbags",
      oldprice: "US$ 1.831,00",
      off: "27% OFF",
      newprice: "1.329",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/45/45744274db_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Handbags",
      oldprice: "US$ 913,00",
      off: "31% OFF",
      newprice: "623",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46912561oj_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Sunglasses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/49/49835502ms_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Blazers",
      oldprice: "US$ 2.835,00",
      off: "27% OFF",
      newprice: "2.059",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46920887bg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Hats",
      oldprice: "US$ 422,00",
      off: "22% OFF",
      newprice: "326",
      category: "men",
      size: "M",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46918603ea_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Sunglasses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "99",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46917322kh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Scarves and foulards",
      oldprice: "US$ 619,00",
      off: "34% OFF",
      newprice: "408",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46918621pf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Sunglasses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46917418mb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Scarves and foulards",
      oldprice: "US$ 619,00",
      off: "34% OFF",
      newprice: "408",
      category: "men",
      size: "XXS XS S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46912495tc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "BALENCIAGA",
      microcategory: "Sunglasses",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "59",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17566396km_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "Y-3",
      microcategory: "Sneakers",
      oldprice: "US$ 692,00",
      off: "27% OFF",
      newprice: "502",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17567048ro_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "Y-3",
      microcategory: "Sneakers",
      oldprice: "US$ 461,00",
      off: "27% OFF",
      newprice: "335",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10121133bm_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "NEIL BARRETT",
      microcategory: "T-shirts",
      oldprice: "US$ 405,00",
      off: "27% OFF",
      newprice: "294",
      category: "men",
      size: "42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17567076ro_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "Y-3",
      microcategory: "Sneakers",
      oldprice: "US$ 461,00",
      off: "27% OFF",
      newprice: "335",
      category: "men",
      size: "40 41 41.5 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10004551oe_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "Y-3",
      microcategory: "Hooded sweatshirts",
      oldprice: "US$ 417,00",
      off: "29% OFF",
      newprice: "293",
      category: "men",
      size: "41 41 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/49/49846265id_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "NEIL BARRETT",
      microcategory: "Blazers",
      oldprice: "US$ 1.302,00",
      off: "38% OFF",
      newprice: "802",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/49/49846082ln_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "NEIL BARRETT",
      microcategory: "Blazers",
      oldprice: "US$ 1.264,00",
      off: "38% OFF",
      newprice: "779",
      category: "men",
      size: "43",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30055984ht_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Casual pants",
      oldprice: "US$ 178,00",
      off: "34% OFF",
      newprice: "116",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30031952sd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Casual pants",
      oldprice: "US$ 178,00",
      off: "34% OFF",
      newprice: "116",
      category: "men",
      size: "40.5",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30031942vw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "US$ 237,00",
      off: "34% OFF",
      newprice: "155",
      category: "men",
      size: "45.5",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30027387gh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "XL",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30027177gi_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30040072mr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "US$ 178,00",
      off: "34% OFF",
      newprice: "116",
      category: "men",
      size: "M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30040007sl_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Shorts & Bermuda",
      oldprice: "US$ 165,00",
      off: "34% OFF",
      newprice: "108",
      category: "men",
      size: "50",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30037254jf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "US$ 237,00",
      off: "34% OFF",
      newprice: "155",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30036429dd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30026970mi_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30040096ig_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Shorts & Bermuda",
      oldprice: "US$ 108,00",
      off: "34% OFF",
      newprice: "71",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30036297ju_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "US$ 237,00",
      off: "34% OFF",
      newprice: "155",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30030143vu_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "US$ 237,00",
      off: "34% OFF",
      newprice: "155",
      category: "men",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30028959dd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30028935tt_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30028916qo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "99",
    },
    {
      image:
        "https://www.yoox.com/images/items/16/16228864xx_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Coats",
      oldprice: "US$ 229,00",
      off: "34% OFF",
      newprice: "149",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30030016jw_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "US$ 237,00",
      off: "34% OFF",
      newprice: "155",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30028946wv_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Denim pants",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "XXS XS S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10118497rd_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "T-shirts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "59",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10112820qc_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "Basic T-shirt",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10112544wo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "T-shirts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "S M",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10112402vi_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "T-shirts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "42 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10112390hv_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "T-shirts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "40 41 41.5 42",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10112701ad_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "EDWIN",
      microcategory: "T-shirts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "41 41 44",
    },
    {
      image:
        "https://www.yoox.com/images/items/47/47336411av_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "ALEXANDER MCQUEEN",
      microcategory: "Swim shorts",
      oldprice: "US$ 350,00",
      off: "39% OFF",
      newprice: "213",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30051759rs_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Casual pants",
      oldprice: "US$ 76,00",
      off: "34% OFF",
      newprice: "50",
      category: "men",
      size: "43",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30027188dx_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Denim pants",
      oldprice: "US$ 170,00",
      off: "34% OFF",
      newprice: "111",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10146190tf_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MALO",
      microcategory: "Shirt",
      oldprice: "US$ 442,00",
      off: "27% OFF",
      newprice: "322",
      category: "men",
      size: "40.5",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30052055fr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Denim pants",
      oldprice: "US$ 165,00",
      off: "35% OFF",
      newprice: "107",
      category: "men",
      size: "45.5",
    },
    {
      image:
        "https://www.yoox.com/images/items/45/45743770mq_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Cross-body bags",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "XL",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17566614ht_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "Y-3",
      microcategory: "Sneakers",
      oldprice: "US$ 538,00",
      off: "27% OFF",
      newprice: "391",
      category: "men",
      size: "L",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46917130qo_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Fabric belts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "M",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30040094wn_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Denim pants",
      oldprice: "US$ 138,00",
      off: "34% OFF",
      newprice: "90",
      category: "men",
      size: "50",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10157183kh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Sweatshirts",
      oldprice: "US$ 89,00",
      off: "34% OFF",
      newprice: "58",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46917005qv_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Hats",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "32W-34L",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30029268fh_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Denim pants",
      oldprice: "US$ 160,00",
      off: "35% OFF",
      newprice: "104",
      category: "men",
      size: "48",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17529783bg_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "VALSPORT",
      microcategory: "Sneakers",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/30/30032521xa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Denim pants",
      oldprice: "US$ 170,00",
      off: "34% OFF",
      newprice: "111",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46916938sx_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Hats",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "S",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17566515cr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "Y-3",
      microcategory: "Sneakers",
      oldprice: "US$ 461,00",
      off: "27% OFF",
      newprice: "335",
      category: "men",
      size: "39 ?",
    },
    {
      image:
        "https://www.yoox.com/images/items/46/46917152xa_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "Leather belts",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "M",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14345403cr_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "JOHN SMEDLEY",
      microcategory: "Sweaters",
      oldprice: "US$ 266,00",
      off: "34% OFF",
      newprice: "174",
      category: "men",
      size: "99",
    },
    {
      image:
        "https://www.yoox.com/images/items/10/10136832ns_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "LEVI'S",
      microcategory: "T-shirts",
      oldprice: "US$ 38,00",
      off: "21% OFF",
      newprice: "30",
      category: "men",
      size: "XS",
    },
    {
      image:
        "https://www.yoox.com/images/items/14/14345279wb_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "MALO",
      microcategory: "Sweaters",
      oldprice: "US$ 406,00",
      off: "34% OFF",
      newprice: "264",
      category: "men",
      size: "52",
    },
    {
      image:
        "https://www.yoox.com/images/items/17/17529765je_14_f.jpg?width=210&height=272&impolicy=crop&gravity=Center",
      brand: "VALSPORT",
      microcategory: "Sneakers",
      oldprice: "",
      off: "",
      newprice: "",
      category: "men",
      size: "41",
    },
  ]);
  res.send("done boss");
});
app.use("/users", userRouter);
app.use(authCheck);

app.listen(process.env.port, () => {
  console.log(`server running on port ${process.env.port}`);
  try {
    connectDb(process.env.mongoUrl);
    console.log("connectd to db");
  } catch (error) {
    console.log(error);
  }
});
